### ISSUE TITLE
Emacs 27.1 regression ?

### ISSUE THREAD

**Issue by Geod24** [Emacs-D-Mode-Maintainers/Emacs-D-Mode#100]
Just upgraded to Emacs v27.1 on my Macbook, and got greeted with:
```
Eval error in the ‘c-lang-defvar’ or ‘c-lang-setvar’ for ‘c++-template-syntax-table’ (fallback source eval - d-mode compiled with CC Mode 5.33.2 but loaded with 5.34.1): (error "‘c++-make-template-syntax-table’ got no (prior) value in d-mode (might be a cyclic reference)")
```

Will downgrade Emacs, but any pointer ?

**Comment by nordlow** [comment]
Try recompiling d-mode.

**Comment by Geod24** [comment]
> Try recompiling d-mode.el inside the new Emacs.

Originally did that to no effect, but trying the upgrade again just worked. So closing as user error.
