### ISSUE TITLE
Wrong syntax highlight for WYSIWYG strings

### ISSUE THREAD

**Issue by Geod24** [Emacs-D-Mode-Maintainers/Emacs-D-Mode#105]
<img width="343" alt="Screen Shot 2021-01-20 at 0 48 25" src="https://user-images.githubusercontent.com/2180215/105058260-5e271000-5ab9-11eb-9d8c-77f6334a4125.png">

```D
    unittest
    {
        assert(absolute("/"[]) == true);
        assert(absolute(""[]) == false);

        version (Windows)
        {
            assert(absolute(r"\"[]) == true);
            assert(absolute(r"\\"[]) == true);
            assert(absolute(r"c:"[]) == true);
        }
    }
```

https://github.com/dlang/dmd/blob/8e5d57628f107b1d8e3b9bd7d788406cb3d5d768/src/dmd/root/filename.d#L141-L152

**Comment by CyberShadow** [comment]
Apparently, this string syntax is completely unimplemented, and never has been.

**Comment by Geod24** [comment]
Thanks!

**Comment by CyberShadow** [comment]
You're very welcome, @Geod24 :) Thank you for all your work on D.
