### ISSUE TITLE
Incorrect indentation of align(N) aggregate

### ISSUE THREAD

**Issue by nordlow** [Emacs-D-Mode-Maintainers/Emacs-D-Mode#109]
Current indentation

```d
align(1) struct name
         {
}
```

should instead be

```d
align(1) struct name
{
}
```
. Same goes for `union`, `class` and `interface`.

The expression `(1)` is likely the cause.

**Comment by jibal** [comment]
@nordlow 

"align" should be added to the c-paren-nontype-kwds list in d-mode.el, along with "typeof" and "package"

**Comment by CyberShadow** [comment]
@jibal Applied, thanks again.
