### ISSUE TITLE
Missing fontification of member function names returning a typeof(this)

### ISSUE THREAD

**Issue by nordlow** [Emacs-D-Mode-Maintainers/Emacs-D-Mode#110]
For instance in,

```d
typeof(this) getThis() {
    return this;
}
```

`getThis` is not fontified.

**Comment by CyberShadow** [comment]
What is the problem?

**Comment by nordlow** [comment]
> What is the problem?

`getThis` is not fontified.

**Comment by jibal** [comment]
@nordlow 

It seems that no one is maintaining this.

Your issue can be solved by adding "typeof" to the c-modifier-kwds and c-paren-nontype-kwds lists in d-mode.el

No guarantees that this won't have negative effects.

**Comment by CyberShadow** [comment]
@jibal Thank you for that tip, I applied your suggestion and the test suite passed, so I've pushed it to master.
