### ISSUE TITLE
Error when missing strings and unbalanced parenthesis

### ISSUE THREAD

**Issue by Geod24** [Emacs-D-Mode-Maintainers/Emacs-D-Mode#112]
Step one: Type the following:
```D
void main ()
{
    foo(
}
```

Step two: Add `"bar");`. This is what I get:
<img width="118" alt="Screen Shot 2021-06-07 at 16 50 25" src="https://user-images.githubusercontent.com/2180215/120979336-77063880-c7b0-11eb-9cd1-d268bdf9cee7.png">

It also happens when I open the file and remove the last parenthesis.

Versions:
```
    Version: 20210119.1853
     Commit: 199743df55c6bfce3cdb08405bd8519768c8dfa9
     GNU Emacs 27.2 (Mac OSX)
```

**Comment by nordlow** [comment]
Me too.

**Comment by GiulioCocconi** [comment]
Me too

**Comment by Geod24** [comment]
@CyberShadow Any chance you could look into this? Or is any Emacs work pending due to your tree sitter plans?

**Comment by CyberShadow** [comment]
I had a quick look a while ago and couldn't figure out what's wrong :(

It seems to be due to a change in cc-mode, but it only affects d-mode apparently.

> Or is any Emacs work pending due to your tree sitter plans?

I think this bug is what got me looking into tree-sitter for D/Emacs, but it's a large project for which I don't know if I'll have time soon.

I've been personally working around this bug by putting `// "` at the end of my D files.

**Comment by radenling** [comment]
I looked into this and it seems cc-mode has updated how it handles multiline strings which I think is the cause.

Replacing:
```elisp
(c-lang-defconst c-multiline-string-start-char
  ;; Set to true to indicate that D doesn't mind raw embedded newlines in strings
d t)
```

with:
 ```elisp
(c-lang-defconst c-ml-string-opener-re
  d "\\(\\(\"\\)\\)")

(c-lang-defconst c-ml-string-max-opener-len
  d 1)

(c-lang-defconst c-ml-string-any-closer-re
  d "\\(\\(\"\\)\\)")

(c-lang-defconst c-ml-string-max-closer-len
  d 1)
```
solves the problem and doesn't seem to break anything. There is a comment in the cc-mode source saying that `c-multiline-string-start-char` is being deprecated. `c-ml-string-opener-re` is the new way of handling multiline strings but it's possible to leave the `c-multiline-string-start-char` in there for now to support older cc-mode versions. If both are defined the latter will be used if the cc-mode version is recent enough.

**Comment by radenling** [comment]
Okay, it seems I was incorrect when I said "doesn't seem to break anything". Two tests are failing. I'll look into that and then open a PR.
