### ISSUE TITLE
Inconsistent `enum` highlighting (type name and members)

### ISSUE THREAD

**Issue by Geod24** [Emacs-D-Mode-Maintainers/Emacs-D-Mode#113]
> GNU Emacs 27.2
> D mode: 20210119.1853

```D
enum AddressType
{
    string cname;
    uint ipv4;
    ulong[2] ipv6;
}
```
<img width="136" alt="Screen Shot 2021-09-23 at 15 35 30" src="https://user-images.githubusercontent.com/2180215/134464012-85d9f8b2-8730-4037-9bde-2e8fa0ddb2f5.png">

Issues:
- First member's identifier is not properly highlighted;
- `enum`'s name is highlighted as an identifier, not a type;

```diff
-enum AddressType
+private enum AddressType
```
<img width="177" alt="Screen Shot 2021-09-23 at 15 35 45" src="https://user-images.githubusercontent.com/2180215/134464140-89034005-5a83-4393-aa9c-4170b22f23ef.png">

As can be seen, adding a visibility qualifier fixes the second issue.
Related: #104

**Comment by CyberShadow** [comment]
What is this syntax? Is it like a `struct`?

**Comment by CyberShadow** [comment]
DMD master says:
```
test.d(3): Error: `string` is not a valid attribute for enum members
test.d(3): Error: `cname` is not a valid attribute for enum members
test.d(3): Error: `;` is not a valid attribute for enum members
test.d(4): Error: `uint` is not a valid attribute for enum members
test.d(4): Error: `ipv4` is not a valid attribute for enum members
test.d(4): Error: `;` is not a valid attribute for enum members
test.d(5): Error: `ulong` is not a valid attribute for enum members
test.d(5): Error: `[` is not a valid attribute for enum members
test.d(5): Error: `2` is not a valid attribute for enum members
test.d(5): Error: `]` is not a valid attribute for enum members
test.d(5): Error: `ipv6` is not a valid attribute for enum members
test.d(5): Error: `;` is not a valid attribute for enum members
```

I don't know what language this is, but it doesn't seem to be D, so I think supporting this syntax is out-of-scope for this package. :)

**Comment by Geod24** [comment]
🤦 

Yes, I just realized I mistakenly substituted `union` for `enum`. Sorry for the noise!
