### ISSUE TITLE
incorrect treatment of wysiwyg string literals

### ISSUE THREAD

**Issue by John-Colvin** [Emacs-D-Mode-Maintainers/Emacs-D-Mode#21]
Escape sequences are mistakenly still recognised in wysiwyg strings, meaning that something like
```D
`fdas\`
```
isn't recognised as being terminated by the closing `

**Comment by russel** [comment]
Dmitri Makarov (@dmakarov) seems to have found a way of fixing this problem (#21, #25, #45); it certainly seems to fix it on my test programs. Excellently done Dmitri and many thanks.

**Comment by CyberShadow** [comment]
Seems like this has regressed in Emacs snapshots:

https://travis-ci.org/Emacs-D-Mode-Maintainers/Emacs-D-Mode/jobs/166395125

**Comment by CyberShadow** [comment]
Fails since https://github.com/emacs-mirror/emacs/commit/db2ee1cd63ebebbe52099a1442dbc47f74135e5b

**Comment by CyberShadow** [comment]
Fontification becomes correct if the backtick is deleted and re-added... perhaps this is a case of https://github.com/Emacs-D-Mode-Maintainers/Emacs-D-Mode/issues/49.

**Comment by CyberShadow** [comment]
Fixed in e81e5f7d1e35fcafd3180cf1fded2a5eae955d69. #49 remains unfixed.
