### ISSUE TITLE
void-function set-difference error

### ISSUE THREAD

**Issue by swsnr** [Emacs-D-Mode-Maintainers/Emacs-D-Mode#23]
D Mode uses `set-difference` from `cl` without requiring `cl`, which causes a `void-function` error if `cl` is not loaded.

You need a `(require 'cl)`.

**Comment by aestiff** [comment]
This issue seems to have crept back into the codebase. I was getting the same problems on compilation this weekend, and was able to correct it by inserting the (require 'cl) in d-mode.el locally.
