### ISSUE TITLE
Sluggish and Incorrectly Highlighted Type-Qualified Enums

### ISSUE THREAD

**Issue by nordlow** [Emacs-D-Mode-Maintainers/Emacs-D-Mode#33]
On latest stable Emacs 24.4.1 d-mode.el's parsing and syntax highlightning doesn't work correctly for type-qualified enums such as

``` D
enum BasicEmotions:ubyte
{
    fear, // some comment
    anger, // some other comment
}
```

eventhough my `d-mode.el` contains the section

``` Emacs-Lisp
(c-lang-defconst c-colon-type-list-kwds
  ;; Keywords that may be followed (not necessarily directly) by a colon
  ;; and then a comma separated list of type identifiers.
  d  '("class" "enum" "interface"))
```

The coloring is flashy and makes interaction sluggish for enums with many enumerators.

Highly annoying.

Anybody know a solution?

Do we need to fix d-mode.el or Emacs' builtin cc-mode stuff?

**Comment by CyberShadow** [comment]
Almost certainly same root cause as #19. (See https://github.com/Emacs-D-Mode-Maintainers/Emacs-D-Mode/pull/93/commits/af0ee16ed0005933f7d5811d4252386150110542 for a possible fix)
