### ISSUE TITLE
[ENH/BUG] Support version / else version / else pattern

### ISSUE THREAD

**Issue by mathias-lang-sociomantic** [Emacs-D-Mode-Maintainers/Emacs-D-Mode#39]
According to [the specs](http://dlang.org/version.html#VersionCondition), the following code:

````
version (SomeVersion)
{
}
else
    version (SomeOtherVersion)
    {
    }
else
{
    static assert (0, "Fail");
}
````

Should have the last `else` indented at the same level as `version (SomeOtherVersion)`.

However, one common idiom is the following:
````
version (SomeVersion)
{
}
else version (SomeOtherVersion)
{
}
else
{
    static assert (0, "Fail");
}
````

Which basically allow us to use `version` as `if`. would it been possible to get both (bug fixed when `version` is on a newline after an `else`, and right alignment of braces when we have `else version`) ?

**Comment by dmakarov** [comment]
The same problem exists for `debug` statements:
```d
  debug (A)
  {
  }
  else debug (B)
       {
       }
  else
  {
  }
```
The syntactic analysis that determines how code to be indented is built into the cc-mode engine and doesn't allow customization, i.e. addition of custom syntactic clauses. To fix this issues it is necessary either to reimplement the syntactic analysis for D mode, or to add D mode to the built-in languages of cc-mode.

**Comment by russel** [comment]
Pull request duly committed. I didn't get chance to test it out fully, but took the small risk and committed it anyway. We can always back out if problems arise.
