### ISSUE TITLE
Error "c-add-stmt-syntax: Symbol's function definition is void: add-function"

### ISSUE THREAD

**Issue by fasiha** [Emacs-D-Mode-Maintainers/Emacs-D-Mode#40]
I type the following into Emacs (GNU Emacs 24.3.1 (x86_64-apple-darwin11.4.2, Carbon Version 1.6.0 AppKit 1138.51)) after installing d-mode via `package-install`:
```
import std.stdio;
void main() {
  string s = "hi there";
}
```
Upon completing the final closing-brace, Emacs gives the error (in `*Messages*`): `c-add-stmt-syntax: Symbol's function definition is void: add-function`.

Further text entered inside `main` won't be correctly indented, with the above error being continually given.

**Comment by dmakarov** [comment]
You may want to upgrade to a later version of Emacs. If you use homebrew, `brew install --with-cocoa --devel emacs` probably will solve the issue. Even `--HEAD` instead of `--devel` may be worth trying.

**Comment by fasiha** [comment]
@dmakarov thanks, upgrading to `--devel` did the trick! But I needed `--cocoa` not `--with-cocoa` (brew didn't complain about the latter…).
