### ISSUE TITLE
Create package testing infrastructure.

### ISSUE THREAD

**Issue by dmakarov** [Emacs-D-Mode-Maintainers/Emacs-D-Mode#42]
I created a basic infrastructure to test d-mode package. For now, it only checks whether the package compiles or not.  In future I hope to add tests to validate that d-mode can analyze D source files correctly. In my opinion it's already useful to verify automatically that the package compiles on a pull request.

It's now on testing branch of my fork and linked to travis-ci and coveralls continuous integration servers. https://github.com/dmakarov/Emacs-D-Mode/tree/testing

If you consider it valuable and are interested in having it in the main repository, I will merge it to my master branch and submit a pull request.  The links in README.md will have to be updated and Emacs-D-Mode-Maintainers accounts on travis-ci.org and coveralls.io have to be connected to Emacs-D-Mode repository. As far as I understand this should not affect how the package is pushed to and distributed by ELPA.

**Comment by russel** [comment]
All software needs tests, even ELisp code, so some tests are better than the none we have now. So yes I think we should merge this into mainline master.

**Comment by CyberShadow** [comment]
Fixed by https://github.com/Emacs-D-Mode-Maintainers/Emacs-D-Mode/pull/46 ?

**Comment by russel** [comment]
Yes this is fixed by #46. I should have spotted this earlier!
