### ISSUE TITLE
Different package highlight for import

### ISSUE THREAD

**Issue by mathias-lang-sociomantic** [Emacs-D-Mode-Maintainers/Emacs-D-Mode#54]
Currently those two lines are highlighted differently:

``` D
import foo.bar;
import foo.Bar;
```

The later line has the package in purple, and the module in green, while the former has the package uncoloured.

```
GNU Emacs 25.1.50.1
d-mode             20151205.2354 installed             D Programming Language major mode for (X)Emacs
```

**Comment by CyberShadow** [comment]
The highlighting artifact seems to be caused that d-mode inherits java-mode's package highlighting logic. In Java, the last part of an import is almost always either `*` or a type (which are typically camel-cased).

Curious that GitHub has a similar issue in its highlighting :)
