### ISSUE TITLE
Indentation is wrong for an enum with EnumBaseType

### ISSUE THREAD

**Issue by landaire** [Emacs-D-Mode-Maintainers/Emacs-D-Mode#56]
For an enum with a base type:

```
  enum : char {
    eof = cast(char)-1,
      openParen = '(',
      closeParen = ')',
      comment = ';'
  };
```

The indentation for all lines after the first (in this case eof) are indented one extra level. This does not occur with enums that don't have a base type specified.

**Comment by russel** [comment]
I believe this is a duplicate of #19.

**Comment by CyberShadow** [comment]
Closing per Russel's comment.
