### ISSUE TITLE
Contracts are more indented than body

### ISSUE THREAD

**Issue by mathias-lang-sociomantic** [Emacs-D-Mode-Maintainers/Emacs-D-Mode#58]
The following is the indentation I get for contracts:

``` D
double foo (double b)
    in
    {
        assert(b == b);
    }
out (result)
    {
        assert(result == result);
    }
body
{
    return b;
}
```

``` D
double foo (double b)
    out (result)
        {
            assert(result == result);
        }
body
{
    return b;
}
```

``` D
double foo (double b)
    in
    {
        assert(b == b);
    }
body
{
    return b;
}
```

My settings are:

``` lisp
(setq-default indent-tabs-mode nil)
(setq-default tab-width 4)
(defvaralias 'c-basic-offset 'tab-width)
(setq c-default-style "bsd" c-basic-offset 4)
```

But it happens when commenting those lines out too.

**Comment by nordlow** [comment]
Incorrect indentation still happens for me. Can you point to a place in d-mode.el that controls this behaviour?

**Comment by CyberShadow** [comment]
> Incorrect indentation still happens for me.

Please don't forget to configure the offset according to your preference. (`C-c C-o`)

> Can you point to a place in d-mode.el that controls this behaviour?

Please see `d-in-knr-argdecl`.

**Comment by nordlow** [comment]
> Please see `d-in-knr-argdecl`.

Thanks! Would it be possible to have

(c-set-offset 'knr-argdecl-intro 0)

be called automatically upon entering of `d-mode`, provide `d-mode.el` has been loaded?

**Comment by CyberShadow** [comment]
I think the proper way is something like:

```elisp
(c-add-style
 "My D style"
 '((c-offsets-alist . ((knr-argdecl-intro . 0)
                       ;; ...
		       ))))

(defun my/d-mode-hook ()
  (c-set-style "My D style"))
(add-hook 'd-mode-hook 'my/d-mode-hook)
```

**Comment by CyberShadow** [comment]
> What about adding this to d-mode.el?

Sounds good. It should mention that it attempts to implement https://dlang.org/dstyle.html as closely as possible.

**Comment by nordlow** [comment]
> > What about adding this to d-mode.el?
> 
> Sounds good. It should mention that it attempts to implement https://dlang.org/dstyle.html as closely as possible.

Do you want to add it or shall I?

**Comment by CyberShadow** [comment]
Yes, please submit a pull request.

If you could include a test that covers all of the offset settings, that would be great.

**Comment by nordlow** [comment]
Should it be activated by default via a hook?

**Comment by CyberShadow** [comment]
Not by default I think (unless that's common practice for cc-mode-based major modes? but even then I'm not sure about changing the current default), but we can document how to enable it in the README.
