### ISSUE TITLE
Compilation errors from builds using dub (or using the -vcolumns dmd flags) are not recognized in compilation buffer

### ISSUE THREAD

**Issue by jeanbaptistelab** [Emacs-D-Mode-Maintainers/Emacs-D-Mode#59]
Hi,

I've been scratching my head for a while as to why the compilation buffer wouldn't highlight compilation error messages when building a project with dub until I realized that dub adds the [`-vcolumns`](https://dlang.org/dmd-linux.html#switch-vcolumns) command line option to dmd.

I fixed this by adding the following new entry to the compilation-error-regexp-alist list.

    (add-to-list 'compilation-error-regexp-alist-alist
        '(dmd-vcolumns
            "^\\([^ \n]+\\)(\\([0-9]+\\),\\([0-9]+\\)): \\(?:Error\\|.\\|warnin\\(g\\)\\|remar\\(k\\)\\)"
            1 2 3 (4 . 5)))
    (add-to-list 'compilation-error-regexp-alist 'dmd-vcolumns)

Feel free to merge this under the same license as the rest of the code.

Cheers,

JB

**Comment by CyberShadow** [comment]
See https://github.com/Emacs-D-Mode-Maintainers/Emacs-D-Mode/pull/69

**Comment by CyberShadow** [comment]
Should be fixed now that #69 is merged.
