### ISSUE TITLE
Exponential fontification time of backslashes in WYSIWYG-literals

### ISSUE THREAD

**Issue by CyberShadow** [Emacs-D-Mode-Maintainers/Emacs-D-Mode#64]
This line takes a second or two to fontify:

```
  `\\aaa\\aaa\\aaa\\aaa\\aaa\\aaa
```

Curiously, this is true even when it's inside a comment.

**Comment by russel** [comment]
I believe the merged pull request solves this issue. Thanks @CyberShadow for posting it.
