### ISSUE TITLE
dfmt

### ISSUE THREAD

**Issue by qsimpleq** [Emacs-D-Mode-Maintainers/Emacs-D-Mode#73]
Hello. Recently I found a module [https://github.com/nordlow/elisp/blob/master/mine/dfmt.el](https://github.com/nordlow/elisp/blob/master/mine/dfmt.el) by nordlow.

And I modify it (thanks Syohei Yoshida). The result can be found here [https://github.com/qsimpleq/elisp-dfmt](https://github.com/qsimpleq/elisp-dfmt)

Pls try and test it.

When I wanted to add the recipe to melpa, **milkypostman** say

> i think this package would fit better in the d-mode package. Have you tried reaching out to the maintainers? it would be better as an on-save hook i think.
> [https://github.com/melpa/melpa/pull/4044](url)

So the question is - do the authors wish to include this module in the d-mode?

**Comment by nordlow** [comment]
License has been added here:

https://github.com/nordlow/elisp/blob/master/mine/dfmt.el

**Comment by tmccombs** [comment]
I would love to see some dfmt support in emacs. Currently d-mode really struggles to get formatting correct. For example, if I add a base type to an enum, it messes up the indentation of all the members.

**Comment by CyberShadow** [comment]
Now that dfmt support is a published package, is there still incentive to move it into d-mode? Unless there is the opportunity for tight integration, perhaps packages that depend on external 3rd-party tools are better left separate.
