### ISSUE TITLE
d-mode not working under emacs25

### ISSUE THREAD

**Issue by antoniocorbibellot** [Emacs-D-Mode-Maintainers/Emacs-D-Mode#75]
Hi (and thanks for d-mode! :),

I've just upgraded to emacs 25.1 and d-mode complains (and does not work) with these messages:

    Eval error in the ‘c-lang-defconst’ for ‘c-opt-cpp-prefix’ in d-mode:
    Eval error in the ‘c-lang-defconst’ for ‘c-cpp-matchers’ in d-mode:
    Eval error in the ‘c-lang-defconst’ for ‘c-matchers-1’ in d-mode:
    c-get-lang-constant: Invalid function: "\\s *#\\s *"

Is there any chance to get a fix for this error?
Thanks!
A. Corbi

**Comment by nordlow** [comment]
I have the same problem.

**Comment by antoniocorbibellot** [comment]
@nordlow: Simply recompile d-mode.el with emacs25, that's all.

**Comment by nordlow** [comment]
Ok, thanks. What about the ELPA packages? Are these already prepared for 25.1?

**Comment by antoniocorbibellot** [comment]
@nordlow : I don't think so...but I think that simply deinstalling and reinstalling d-mode will force the recompilation, I have manually recompiled d-mode.el, so I'm not 100% sure here.

**Comment by nordlow** [comment]
How do I do this for all my precompiled ELPA-packages?

**Comment by pheerai** [comment]
Just call `byte-recompile-file` on all of the `.el`-files from within emacs.

Alternatively, just remove the `.elc`-files and work with the uncompiled files until the next version is released, should work as well, although maybe slower.

**Comment by CyberShadow** [comment]
> How do I do this for all my precompiled ELPA-packages?

This StackOveflow page has a succinct answer:

http://stackoverflow.com/questions/24725778/how-to-rebuild-elpa-packages-after-upgrade-of-emacs

As this is not a bug in Emacs-D-Mode, closing.
