### ISSUE TITLE
Project logo

### ISSUE THREAD

**Issue by CyberShadow** [Emacs-D-Mode-Maintainers/Emacs-D-Mode#77]
Currently this project doesn't have a logo.

Here are some simple proposed variants:

<img src="https://dump.thecybershadow.net/3db659ac4c5ebe8820a824c99276fbef/emacs-d-plain.svg" width="400">
<img src="https://dump.thecybershadow.net/29aaba93376e9d1c887bde31b30de8d5/dlogo-emacs-plain.svg" width="400"> 
<img src="https://dump.thecybershadow.net/fef5a5bad93cf476444f409b5927c9bd/dlogo-emacs-with-pen-plain.svg" width=400>

**Comment by russel** [comment]
I like the first two for different reasons. I's be happy with either.

**Comment by CyberShadow** [comment]
I think these proposals are all inadequate today.

On IRC someone said that the first one makes more sense, because it's "D in Emacs", not the other way around. Though, a blue disc and pen don't really strike up an association with Emacs.

More importantly, the D logo with the glossy background has not been used officially in a while, and there is a proposal to replace the D logo with the Dconf logo (http://dconf.org/2017/images/dconf_logo_2017.svg).

**Comment by CyberShadow** [comment]
I went ahead and updated the organization profile picture with the first logo above (previously it had the same profile picture as @russel's account). The motivation was that it was a bit weird how Russel's photo showed up in the "Organizations" section of [github user profiles](https://github.com/CyberShadow), and a person's photo is generally not very descriptive of what the organization or project is about. Hopefully no one minds.

**Comment by CyberShadow** [comment]
I guess let's go with that unless someone comes forth with a better proposal.
