### ISSUE TITLE
Drop support for Emacs 23

### ISSUE THREAD

**Issue by CyberShadow** [Emacs-D-Mode-Maintainers/Emacs-D-Mode#78]
Since it was committed, Dmitri's `.travis.yml` doesn't seem to work any longer. I had a go at fixing it and wasn't successful, so I looked at what other people are doing. Flycheck has a reusable [`emacs-travis.mk`](https://github.com/flycheck/emacs-travis/) project, which seems to be the only actively maintained Travis integration project for Emacs CI. However, it doesn't support anything before 24.3 (not as much its fault, as Emacs' install script apparently not supporting non-root installation back then).

As such, I suggest that we stop supporting Emacs 23, and move forward with breaking changes (such as replacing usage of the `cl` package with non-deprecated replacements). Since the earliest version that `emacs-travis.mk` supports is Emacs 24.3, I suggest that that become our oldest "officially-supported" version.

**Comment by CyberShadow** [comment]
> Since the earliest version that emacs-travis.mk supports is Emacs 24.3, I suggest that that become our oldest "officially-supported" version.

Actually, since https://github.com/Emacs-D-Mode-Maintainers/Emacs-D-Mode/commit/b4cbdfc9bdae0ee1a7c401f616377d7031bbdf27, we don't even fully support 24.3 (though we do acknowledge it by disabling d-mode features that depend on Emacs features which that version doesn't support).

**Comment by russel** [comment]
Maybe we should progress this. Is setting the floor version of Emacs at 24.4 for this mode reasonable? Or even go to 25?

**Comment by CyberShadow** [comment]
We currently automatically test the package with 24.3, so we can safely say that anything newer than that version is supported. Although, there is currently some compatibility code with older versions, so dropping 24.3 might allow getting rid of it.

I'd say to keep the minimal officially supported version at 24.3 until we have a practical reason to drop it.

**Comment by russel** [comment]
Given there have been no voices against, it seems like we have a decision. So let's declare the minimum version of Emacs to be 24.3 and tidy up the code accordingly.
