### ISSUE TITLE
Wrong indentation for `static if` ... `else static if`

### ISSUE THREAD

**Issue by mathias-lang-sociomantic** [Emacs-D-Mode-Maintainers/Emacs-D-Mode#79]
Just upgraded Emacs-D-Mode, so presumably using 98af62e67026fee1dda9155e1a463917fc83802e

```D
void main ()
{
    static if (is(Object))
    {

    }
    else static if (is(Typoe))
         {
         }
}
```

As you can see, the brackets are too indented.

**Comment by CyberShadow** [comment]
Hmm, doesn't happen here. We now even have an actual test for this:
https://github.com/Emacs-D-Mode-Maintainers/Emacs-D-Mode/blob/master/tests/I0039.d#L48-L56

What do you get without any `c-offsets-alist` customizations?

**Comment by mathias-lang-sociomantic** [comment]
Hum, emacs 24.3.1 (which [as I just read](https://github.com/Emacs-D-Mode-Maintainers/Emacs-D-Mode/issues/78#issuecomment-252996831), you're not supporting fully).
I just upgraded to Emacs 26 and that fixed it :+1:

**Comment by CyberShadow** [comment]
Note that indentation for 24.3 and below has been broken [since June](https://github.com/Emacs-D-Mode-Maintainers/Emacs-D-Mode/commit/b4cbdfc9bdae0ee1a7c401f616377d7031bbdf27). Perhaps the change reached you only now because no one has been updating the version header until a few days ago.

**Comment by mathias-lang-sociomantic** [comment]
It was broken for a long time for me, and was extremely annoying, but I didn't bother reporting it because the project was not actively maintained :)
