### ISSUE TITLE
dfmt wrapper?

### ISSUE THREAD

**Issue by russel** [Emacs-D-Mode-Maintainers/Emacs-D-Mode#81]
Per Nordlöw wrote a bit of ELisp last year to make use of dfmt to reformat code in an Emacs buffer. Should we be looking to bring this into the mode?

https://github.com/nordlow/elisp/blob/master/mine/dfmt.el

@nordlow

**Comment by CyberShadow** [comment]
I think that would be fine, though things that are specific to certain software or other Emacs packages should be separated out into their own subpackage, or at least file.

**Comment by MartinNowak** [comment]
Permalink to new version https://github.com/nordlow/elisp/blob/f0b9690e0246a0657ee06011eaa54b78018f3028/mine/dfmt2.el.

**Comment by russel** [comment]
This one is in MELPA.

https://github.com/qsimpleq/elisp-dfmt

**Comment by CyberShadow** [comment]
Considering that:

- d-mode uses cc-mode, which has its own support for formatting (indentation), which can be made to work well (or well enough) for D code as well;
- this feature does require an external dependency;
- a separate package already exists for this dedicated purpose,

I think the current situation is acceptable as far as d-mode is concerned.
