### ISSUE TITLE
Just wonder why the makefile for testing…

### ISSUE THREAD

**Issue by russel** [Emacs-D-Mode-Maintainers/Emacs-D-Mode#83]
…I guess the question is really why the ert-runner is not considered good enough so that a Makefile is needed to drive an Emacs command.

**Comment by CyberShadow** [comment]
Presumably because `make` is much shorter to type than `cask exec emacs -Q -batch -l d-mode-test.el -l d-mode.el -f ert-run-tests-batch-and-exit`, but you would probably need to ask the author, @dmakarov, for an authoritative answer.

**Comment by CyberShadow** [comment]
FWIW, since it was already there, I've used the Makefile for the Travis CI script (see `.travis.yml`).

**Comment by russel** [comment]
I had thought the idiomatic command was:
```
cask exec ert-runner
```

**Comment by CyberShadow** [comment]
I had a look at ert-runner. It seems to require its own directory structure and stuff.

I don't see what there is to gain from switching to a different way of testing d-mode and introducing additional (or different) dependencies, considering that the current one seems to be working just fine and I don't see any issues worth fixing.

If there's some important aspect of this that I missed, please reopen or submit a PR.
