### ISSUE TITLE
highlighting issue with escaped double quote

### ISSUE THREAD

**Issue by MartinNowak** [Emacs-D-Mode-Maintainers/Emacs-D-Mode#84]
In this line https://github.com/dlang/dub-registry/blob/83d960c599dbe70ad6967ee5eda17fc7de7b13e6/source/dubregistry/registry.d#L319 the string opening/closing mechanism starts to be off by one when reverting the buffer not from the top, e.g. put your cursor on that line and execute `revert-buffer`.

**Comment by CyberShadow** [comment]
Looks like an instance of #49.
