### ISSUE TITLE
Escapes within backtip nested in string are ignored

### ISSUE THREAD

**Issue by Geod24** [Emacs-D-Mode-Maintainers/Emacs-D-Mode#90]
The following string trips Emacs-D-Mode:
```
"`\"`"
```

![image](https://user-images.githubusercontent.com/2180215/41453897-726fcba4-70b2-11e8-9197-75a8f53f4160.png)

Emacs-D-Mode: `20180502.710`
Emacs: `GNU Emacs 25.3.1`
OS: `Mac OSX 10.13.5`

**Comment by benjones** [comment]
This code from line 1440 of expression.d in DMD breaks highlighting for the rest of the file: 

```
error("read-modify-write operations are not allowed for `shared` variables. Use `core.atomic.atomicOp!\"%s\"(%s, %s)` instead.", Token.toChars(rmwOp), toChars(), ex ? ex.toChars() : "1");
```

It looks like the \" is treated as the closing quote, rather than a quote literal.
