### ISSUE TITLE
Dead project? 

### ISSUE THREAD

**Issue by RustyRaptor** [Emacs-D-Mode-Maintainers/Emacs-D-Mode#92]
I don't see any activity what happened? Is it worth using d-mode in emacs? The melpa package also says it's obsolete.

**Comment by CyberShadow** [comment]
> I don't see any activity what happened?

Currently, there are no immediately actionable improvements.

If you have the time to research and submit a pull request fixing any of the open issues, I'll try to make sure it's reviewed / merged promptly.

> Is it worth using d-mode in emacs?

Sure, I use it all the time.

> The melpa package also says it's obsolete.

You're probably looking at the entry in `list-packages` showing your local previously-installed version.
