### ISSUE TITLE
Parenthesis-const/immutable qualified function parameters and return types

### ISSUE THREAD

**Issue by nordlow** [Emacs-D-Mode-Maintainers/Emacs-D-Mode#95]
Parenthesis `const`/`immutable` qualified function parameters and return types such as

```D
const(Type) foo(const(Type) param);
```

doesn't fontify first occurrence of `Type`, `foo` and `param`.

**Comment by nordlow** [comment]
https://github.com/CyberShadow/Emacs-D-Mode/commit/703269df0604c656d6300f2f21af18574aba1801 works fine for me!

**Comment by nordlow** [comment]
Declarations such as `void foo(immutable Type var);` now fontfies correctly in latest #93.

**Comment by CyberShadow** [comment]
Thanks for testing. It should be closed automatically when #93 is merged in master.

**Comment by nordlow** [comment]
Great. Thanks again.
